const data = [
  {
    id: 1,
    type: 'specialOffer',
    img: '/images/so1.png',
    name: 'دلمه برگ کلم',
    discount: '%۸',
    discountPrice: '۲۲۰٬۰۰۰',
    price: '۲۰۹٬۰۰۰ تومان',
    star: '۵',
    totalStars: '۵۲ امتیاز',
  },
  {
    id: 2,
    type: 'specialOffer',
    img: '/images/so2.png',
    name: 'بادمجان شکم‌پر',
    discount: '%۱۸',
    discountPrice: '۱۵۰٬۰۰۰',
    price: '۱۳۶٬۰۰۰ تومان',
    star: '۴',
    totalStars: '۳۲ امتیاز',
  },
  {
    id: 3,
    type: 'specialOffer',
    img: '/images/so3.png',
    name: 'کالزونه اسفناج',
    discount: '%۱۷',
    discountPrice: '۱۹۰٬۰۰۰',
    price: '۱۷۷٬۰۰۰ تومان',
    star: '۵',
    totalStars: '۶۲ امتیاز',
  },
  {
    id: 4,
    type: 'specialOffer',
    img: '/images/so4.png',
    name: 'پیتزا قارچ',
    discount: '%۲۵',
    discountPrice: '۲۱۵٬۰۰۰',
    price: '۱۷۵٬۰۰۰ تومان',
    star: '۳',
    totalStars: '۳۳ امتیاز',
  },
  {
    id: 5,
    type: 'specialOffer',
    img: '/images/so5.png',
    name: 'پاستا سبزیجات',
    discount: '%۲۰',
    discountPrice: '۱۷۵۰۰۰',
    price: '۱۵۰۰۰۰ تومان',
    star: '۵',
    totalStars: '۵۰ امتیاز',
  },
  {
    id: 6,
    type: 'specialOffer',
    img: '/images/so1.png',
    name: 'دلمه برگ کلم',
    discount: '%۸',
    discountPrice: '۲۲۰٬۰۰۰',
    price: '۲۰۹٬۰۰۰ تومان',
    star: '۵',
    totalStars: '۵۲ امتیاز',
  },
  {
    id: 7,
    type: 'specialOffer',
    img: '/images/so2.png',
    name: 'بادمجان شکم‌پر',
    discount: '%۱۸',
    discountPrice: '۱۵۰٬۰۰۰',
    price: '۱۳۶٬۰۰۰ تومان',
    star: '۴',
    totalStars: '۳۲ امتیاز',
  },
  {
    id: 8,
    type: 'specialOffer',
    img: '/images/so3.png',
    name: 'کالزونه اسفناج',
    discount: '%۱۷',
    discountPrice: '۱۹۰٬۰۰۰',
    price: '۱۷۷٬۰۰۰ تومان',
    star: '۵',
    totalStars: '۶۲ امتیاز',
  },
  {
    id: 9,
    type: 'specialOffer',
    img: '/images/so4.png',
    name: 'پیتزا قارچ',
    discount: '%۲۵',
    discountPrice: '۲۱۵٬۰۰۰',
    price: '۱۷۵٬۰۰۰ تومان',
    star: '۳',
    totalStars: '۳۳ امتیاز',
  },
  {
    id: 10,
    type: 'specialOffer',
    img: '/images/so5.png',
    name: 'پاستا سبزیجات',
    discount: '%۲۰',
    discountPrice: '۱۷۵۰۰۰',
    price: '۱۵۰۰۰۰ تومان',
    star: '۵',
    totalStars: '۵۰ امتیاز',
  },

  // -------------------------------------------------------------favFood
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  // -------------------------------------------------------------

  {
    id: 11,
    type: 'favFood',
    img: '/images/favFood1.png',
    name: 'پنینی اسفناج',
    discount: '%۱۵',
    discountPrice: '۲۱۰٬۰۰۰',
    price: '۱۹۰٬۰۰۰ تومان',
    star: '۳',
    totalStars: '۲۰ امتیاز',
  },
  {
    id: 12,
    type: 'favFood',
    img: '/images/favFood2.png',
    name: 'پیتزا پپرونی',
    discount: '',
    discountPrice: '',
    price: '۱۰۰٬۰۰۰ تومان',
    star: '۴',
    totalStars: '۵۱ امتیاز',
  },
  {
    id: 13,
    type: 'favFood',
    img: '/images/favFood3.png',
    name: 'راتاتویی',
    discount: '%۴۵',
    discountPrice: '۱۸۰٬۰۰۰',
    price: '۹۵٬۰۰۰ تومان',
    star: '۴',
    totalStars: '۴۳ امتیاز',
  },
  {
    id: 14,
    type: 'favFood',
    img: '/images/favFood4.png',
    name: 'بورانی بادمجان',
    discount: '%۲۲',
    discountPrice: '۱۷۰٬۰۰۰',
    price: '۱۴۸٬۰۰۰ تومان',
    star: '۵',
    totalStars: '۷۵ امتیاز',
  },
  {
    id: 15,
    type: 'favFood',
    img: '/images/favFood5.png',
    name: 'پاکورا گیاهی',
    discount: '%۲۰',
    discountPrice: '۱۷۵۰۰۰',
    price: '۱۵۰۰۰۰ تومان',
    star: '۵',
    totalStars: '۸۰ امتیاز',
  },
  {
    id: 16,
    type: 'favFood',
    img: '/images/favFood1.png',
    name: 'پنینی اسفناج',
    discount: '%۱۵',
    discountPrice: '۲۱۰٬۰۰۰',
    price: '۱۹۰٬۰۰۰ تومان',
    star: '۳',
    totalStars: '۲۰ امتیاز',
  },
  {
    id: 17,
    type: 'favFood',
    img: '/images/favFood2.png',
    name: 'پیتزا پپرونی',
    discount: '',
    discountPrice: '',
    price: '۱۰۰٬۰۰۰ تومان',
    star: '۴',
    totalStars: '۵۱ امتیاز',
  },
  {
    id: 18,
    type: 'favFood',
    img: '/images/favFood3.png',
    name: 'راتاتویی',
    discount: '%۴۵',
    discountPrice: '۱۸۰٬۰۰۰',
    price: '۹۵٬۰۰۰ تومان',
    star: '۴',
    totalStars: '۴۳ امتیاز',
  },
  {
    id: 19,
    type: 'favFood',
    img: '/images/favFood4.png',
    name: 'بورانی بادمجان',
    discount: '%۲۲',
    discountPrice: '۱۷۰٬۰۰۰',
    price: '۱۴۸٬۰۰۰ تومان',
    star: '۵',
    totalStars: '۷۵ امتیاز',
  },
  {
    id: 20,
    type: 'favFood',
    img: '/images/favFood5.png',
    name: 'پاکورا گیاهی',
    discount: '%۲۰',
    discountPrice: '۱۷۵۰۰۰',
    price: '۱۵۰۰۰۰ تومان',
    star: '۵',
    totalStars: '۸۰ امتیاز',
  },

  // -------------------------------------------------------------foreignFood
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  {
    id: 21,
    type: 'foreignFood',
    img: '/images/foreignFood1.png',
    name: 'سوشی',
    discount: '%۱۵',
    discountPrice: '۱۰۰٬۰۰۰',
    price: '۸۵٬۰۰۰ تومان',
    star: '۴',
    totalStars: '۷۰ امتیاز',
  },
  {
    id: 22,
    type: 'foreignFood',
    img: '/images/foreignFood2.png',
    name: 'راتاتویی',
    discount: '%۴۵',
    discountPrice: '۱۸۰٬۰۰۰',
    price: '۹۵٬۰۰۰ تومان',
    star: '۴',
    totalStars: '۶۰ امتیاز',
  },
  {
    id: 23,
    type: 'foreignFood',
    img: '/images/foreignFood3.png',
    name: 'پاکورا سبزیجات',
    discount: '%۸',
    discountPrice: '۱۲۵٬۰۰۰',
    price: '۱۱۰٬۰۰۰تومان',
    star: '۴',
    totalStars: '۷۵ امتیاز',
  },
  {
    id: 24,
    type: 'foreignFood',
    img: '/images/foreignFood4.png',
    name: 'لازانیا',
    discount: '',
    discountPrice: '',
    price: '۱۵۰۰۰۰ تومان',
    star: '۵',
    totalStars: '۴۸ امتیاز',
  },
  {
    id: 25,
    type: 'foreignFood',
    img: '/images/foreignFood5.png',
    name: 'سالاد خانگی',
    discount: '%۲۰',
    discountPrice: '۱۷۵۰۰۰',
    price: '۱۵۰۰۰۰ تومان',
    star: '۵',
    totalStars: '۵۹ امتیاز',
  },
  {
    id: 26,
    type: 'foreignFood',
    img: '/images/foreignFood1.png',
    name: 'سوشی',
    discount: '%۱۵',
    discountPrice: '۱۰۰٬۰۰۰',
    price: '۸۵٬۰۰۰ تومان',
    star: '۴',
    totalStars: '۷۰ امتیاز',
  },
  {
    id: 27,
    type: 'foreignFood',
    img: '/images/foreignFood2.png',
    name: 'راتاتویی',
    discount: '%۴۵',
    discountPrice: '۱۸۰٬۰۰۰',
    price: '۹۵٬۰۰۰ تومان',
    star: '۴',
    totalStars: '۶۰ امتیاز',
  },
  {
    id: 28,
    type: 'foreignFood',
    img: '/images/foreignFood3.png',
    name: 'پاکورا سبزیجات',
    discount: '%۸',
    discountPrice: '۱۲۵٬۰۰۰',
    price: '۱۱۰٬۰۰۰تومان',
    star: '۴',
    totalStars: '۷۵ امتیاز',
  },
  {
    id: 29,
    type: 'foreignFood',
    img: '/images/foreignFood4.png',
    name: 'لازانیا',
    discount: '',
    discountPrice: '',
    price: '۱۵۰۰۰۰ تومان',
    star: '۵',
    totalStars: '۴۸ امتیاز',
  },
  {
    id: 30,
    type: 'foreignFood',
    img: '/images/foreignFood5.png',
    name: 'سالاد خانگی',
    discount: '%۲۰',
    discountPrice: '۱۷۵۰۰۰',
    price: '۱۵۰۰۰۰ تومان',
    star: '۵',
    totalStars: '۵۹ امتیاز',
  },
];

export default data;
