const data = [
  {
    id: 91,
    type: 'specialOffer',
    img: '/images/so1.png',
    name: 'دلمه برگ کلم',
    discount: '%۸',
    discountPrice: '220000',
    price: '209000',
    star: '5',
    totalStars: '52',
  },
  {
    id: 92,
    type: 'specialOffer',
    img: '/images/so2.png',
    name: 'بادمجان شکم‌پر',
    discount: '%۱۸',
    discountPrice: '150000',
    price: '136000 ',
    star: '4',
    totalStars: '32',
  },
  {
    id: 93,
    type: 'specialOffer',
    img: '/images/so3.png',
    name: 'کالزونه اسفناج',
    discount: '%۱۷',
    discountPrice: '190000',
    price: '177000',
    star: '5',
    totalStars: '62',
  },
  {
    id: 94,
    type: 'specialOffer',
    img: '/images/so4.png',
    name: 'پیتزا قارچ',
    discount: '%۲۵',
    discountPrice: '215000',
    price: '175000 ',
    star: '3',
    totalStars: '33',
  },
  {
    id: 95,
    type: 'specialOffer',
    img: '/images/so5.png',
    name: 'پاستا سبزیجات',
    discount: '%۲۰',
    discountPrice: '175000',
    price: '150000 ',
    star: '5',
    totalStars: '50',
  },
  {
    id: 96,
    type: 'specialOffer',
    img: '/images/so1.png',
    name: 'دلمه برگ کلم',
    discount: '%۸',
    discountPrice: '220000',
    price: '209000',
    star: '5',
    totalStars: '52',
  },
  {
    id: 97,
    type: 'specialOffer',
    img: '/images/so2.png',
    name: 'بادمجان شکم‌پر',
    discount: '%۱۸',
    discountPrice: '150000',
    price: '136000 ',
    star: '4',
    totalStars: '32',
  },
  {
    id: 98,
    type: 'specialOffer',
    img: '/images/so3.png',
    name: 'کالزونه اسفناج',
    discount: '%۱۷',
    discountPrice: '190000',
    price: '177000',
    star: '5',
    totalStars: '62',
  },
  {
    id: 99,
    type: 'specialOffer',
    img: '/images/so4.png',
    name: 'پیتزا قارچ',
    discount: '%۲۵',
    discountPrice: '215000',
    price: '175000 ',
    star: '3',
    totalStars: '33',
  },
  {
    id: 910,
    type: 'specialOffer',
    img: '/images/so5.png',
    name: 'پاستا سبزیجات',
    discount: '%۲۰',
    discountPrice: '175000',
    price: '150000 ',
    star: '5',
    totalStars: '50',
  },

  // -------------------------------------------------------------favFood
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  // -------------------------------------------------------------

  {
    id: 911,
    type: 'favFood',
    img: '/images/favFood1.png',
    name: 'پنینی اسفناج',
    discount: '%۱۵',
    discountPrice: '210000',
    price: '190000',
    star: '3',
    totalStars: '20',
  },
  {
    id: 912,
    type: 'favFood',
    img: '/images/favFood2.png',
    name: 'پیتزا پپرونی',
    discount: '',
    discountPrice: '',
    price: '100000 ',
    star: '4',
    totalStars: '51',
  },
  {
    id: 913,
    type: 'favFood',
    img: '/images/favFood3.png',
    name: 'راتاتویی',
    discount: '%۴۵',
    discountPrice: '180000',
    price: '95000 ',
    star: '4',
    totalStars: '43',
  },
  {
    id: 914,
    type: 'favFood',
    img: '/images/favFood4.png',
    name: 'بورانی بادمجان',
    discount: '%۲۲',
    discountPrice: '170000',
    price: '148000',
    star: '5',
    totalStars: '75',
  },
  {
    id: 915,
    type: 'favFood',
    img: '/images/favFood5.png',
    name: 'پاکورا گیاهی',
    discount: '%۲۰',
    discountPrice: '175000',
    price: '150000 ',
    star: '5',
    totalStars: '80',
  },
  {
    id: 916,
    type: 'favFood',
    img: '/images/favFood1.png',
    name: 'پنینی اسفناج',
    discount: '%۱۵',
    discountPrice: '210000',
    price: '190000',
    star: '3',
    totalStars: '20',
  },
  {
    id: 917,
    type: 'favFood',
    img: '/images/favFood2.png',
    name: 'پیتزا پپرونی',
    discount: '',
    discountPrice: '',
    price: '100000 ',
    star: '4',
    totalStars: '51',
  },
  {
    id: 918,
    type: 'favFood',
    img: '/images/favFood3.png',
    name: 'راتاتویی',
    discount: '%۴۵',
    discountPrice: '180000',
    price: '95000 ',
    star: '4',
    totalStars: '43',
  },
  {
    id: 919,
    type: 'favFood',
    img: '/images/favFood4.png',
    name: 'بورانی بادمجان',
    discount: '%۲۲',
    discountPrice: '170000',
    price: '148000',
    star: '5',
    totalStars: '75',
  },
  {
    id: 920,
    type: 'favFood',
    img: '/images/favFood5.png',
    name: 'پاکورا گیاهی',
    discount: '%۲۰',
    discountPrice: '175000',
    price: '150000 ',
    star: '5',
    totalStars: '80 ',
  },

  // -------------------------------------------------------------foreignFood
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  // -------------------------------------------------------------
  {
    id: 921,
    type: 'foreignFood',
    img: '/images/foreignFood1.png',
    name: 'سوشی',
    discount: '%۱۵',
    discountPrice: '100000',
    price: '85000 ',
    star: '4',
    totalStars: '70',
  },
  {
    id: 922,
    type: 'foreignFood',
    img: '/images/foreignFood2.png',
    name: 'راتاتویی',
    discount: '%۴۵',
    discountPrice: '180000',
    price: '95000 ',
    star: '4',
    totalStars: '60',
  },
  {
    id: 923,
    type: 'foreignFood',
    img: '/images/foreignFood3.png',
    name: 'پاکورا سبزیجات',
    discount: '%۸',
    discountPrice: '125000',
    price: '110000',
    star: '4',
    totalStars: '75',
  },
  {
    id: 924,
    type: 'foreignFood',
    img: '/images/foreignFood4.png',
    name: 'لازانیا',
    discount: '',
    discountPrice: '',
    price: '150000 ',
    star: '5',
    totalStars: '48',
  },
  {
    id: 925,
    type: 'foreignFood',
    img: '/images/foreignFood5.png',
    name: 'سالاد خانگی',
    discount: '%۲۰',
    discountPrice: '175000',
    price: '150000 ',
    star: '5',
    totalStars: '59',
  },
  {
    id: 926,
    type: 'foreignFood',
    img: '/images/foreignFood1.png',
    name: 'سوشی',
    discount: '%۱۵',
    discountPrice: '100000',
    price: '85000 ',
    star: '4',
    totalStars: '70',
  },
  {
    id: 927,
    type: 'foreignFood',
    img: '/images/foreignFood2.png',
    name: 'راتاتویی',
    discount: '%۴۵',
    discountPrice: '180000',
    price: '95000 ',
    star: '4',
    totalStars: '60',
  },
  {
    id: 928,
    type: 'foreignFood',
    img: '/images/foreignFood3.png',
    name: 'پاکورا سبزیجات',
    discount: '%۸',
    discountPrice: '125000',
    price: '110000',
    star: '4',
    totalStars: '75',
  },
  {
    id: 929,
    type: 'foreignFood',
    img: '/images/foreignFood4.png',
    name: 'لازانیا',
    discount: '',
    discountPrice: '',
    price: '150000 ',
    star: '5',
    totalStars: '48',
  },
  {
    id: 930,
    type: 'foreignFood',
    img: '/images/foreignFood5.png',
    name: 'سالاد خانگی',
    discount: '%۲۰',
    discountPrice: '175000',
    price: '150000 ',
    star: '5',
    totalStars: '59',
  },
];

export default data;
